### ISSUE TITLE
not found file R.raw.persianwords

### ISSUE THREAD

**Issue by yahya-tj** [dlyongemallo/persian-ime#5]
Hi, I'm Android developer in Tajikistan. I want to create the Tajik keyboard for Android devices. On the GitHub I found a source code, but not found in the assets R.raw.persianwords files. Tell me, please, file structure persianwords.
sorry for my english is my first language is Tajik.

**Comment by Bizhanmp** [comment]
Hi.
1- create a raw folder in res folder.
2- create a file without type-extension and with "persianwords"
3- add some words with at this file and separate words with "Enter"
